### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zephyrchien** [zephyrchien/realm#3]
- [x] zero copy
- [x] tcp fast open (Linux>=4.11, Windows, BSD; Linux>=3.7 **without** `zero-copy`)
- [ ] ~~tcp fast open (Linux>3.7 **with** `zero-copy`)~~ 
- [x] bind outbound ip or address 
- [x] bind outbound interface
- [x] custom dns servers
- [x] options to turn on/off `tfo`, `zero-copy`
- [x] daemonize
- [x] timeout 
- [x] error handle 
- [x] logger

**Comment by zephyrchien** [comment]
- [x] cmd override
- [x] proxy protocol
- [x] toml
- [ ] traffic statistic
- [x] option for single/multi thread(s)

**Comment by kdurov** [comment]
你好，能麻烦release里面加上update log相关内容吗。
不知道有没有升级需求不敢乱升级。

**Comment by zephyrchien** [comment]
> 你好，能麻烦release里面加上update log相关内容吗。 不知道有没有升级需求不敢乱升级。

看git log; 建议用rc11+(重构了转发部分)，或者直接用最新版本，配置都是向后兼容的
